services:
  backend:
    build: 
      context: ./backend
      dockerfile_inline: |
        FROM node:18
        RUN apt update ; apt upgrade -y
        WORKDIR /usr/app
        COPY package.json .
        RUN npm install
    volumes:
      - ./backend:/usr/app        
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=ride_app
    depends_on:
      postgres:
        condition: service_healthy
    command: sh -c "npm run migration:run && npm run dev"

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ride_app
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: